export type Champion = {
  key: string;
  id: string;
  name: string;
  icon: string; // public 配下のパスを指定: /images/champion/<id>.png
};

/**
 * サンプル定義。public/images/champion 配下に画像を置き、
 * ここに必要なチャンピオンを追加してください。
 */
export const CHAMPIONS: Champion[] = [
  { key: 'Aatrox', id: 'Aatrox', name: 'エイトロックス', icon: '/images/champion/Aatrox.png' },
  { key: 'Ahri', id: 'Ahri', name: 'アーリ', icon: '/images/champion/Ahri.png' },
  { key: 'Akali', id: 'Akali', name: 'アカリ', icon: '/images/champion/Akali.png' },
  { key: 'Akshan', id: 'Akshan', name: 'アクシャン', icon: '/images/champion/Akshan.png' },
  { key: 'Alistar', id: 'Alistar', name: 'アリスター', icon: '/images/champion/Alistar.png' },
  { key: 'Amumu', id: 'Amumu', name: 'アムム', icon: '/images/champion/Amumu.png' },
  { key: 'Anivia', id: 'Anivia', name: 'アニビア', icon: '/images/champion/Anivia.png' },
  { key: 'Annie', id: 'Annie', name: 'アニー', icon: '/images/champion/Annie.png' },
  { key: 'Aphelios', id: 'Aphelios', name: 'アフェリオス', icon: '/images/champion/Aphelios.png' },
  { key: 'Ashe', id: 'Ashe', name: 'アッシュ', icon: '/images/champion/Ashe.png' },
  { key: 'AurelionSol', id: 'AurelionSol', name: 'オレリオン・ソル', icon: '/images/champion/AurelionSol.png' },
  { key: 'Azir', id: 'Azir', name: 'アジール', icon: '/images/champion/Azir.png' },
  { key: 'Bard', id: 'Bard', name: 'バード', icon: '/images/champion/Bard.png' },
  { key: 'Belveth', id: 'Belveth', name: 'ベルヴェス', icon: '/images/champion/Belveth.png' },
  { key: 'Blitzcrank', id: 'Blitzcrank', name: 'ブリッツクランク', icon: '/images/champion/Blitzcrank.png' },
  { key: 'Brand', id: 'Brand', name: 'ブランド', icon: '/images/champion/Brand.png' },
  { key: 'Braum', id: 'Braum', name: 'ブラウム', icon: '/images/champion/Braum.png' },
  { key: 'Caitlyn', id: 'Caitlyn', name: 'ケイトリン', icon: '/images/champion/Caitlyn.png' },
  { key: 'Camille', id: 'Camille', name: 'カミール', icon: '/images/champion/Camille.png' },
  { key: 'Cassiopeia', id: 'Cassiopeia', name: 'カシオペア', icon: '/images/champion/Cassiopeia.png' },
  { key: 'Chogath', id: 'Chogath', name: 'チョ＝ガス', icon: '/images/champion/Chogath.png' },
  { key: 'Corki', id: 'Corki', name: 'コーキ', icon: '/images/champion/Corki.png' },
  { key: 'Darius', id: 'Darius', name: 'ダリウス', icon: '/images/champion/Darius.png' },
  { key: 'Diana', id: 'Diana', name: 'ダイアナ', icon: '/images/champion/Diana.png' },
  { key: 'DrMundo', id: 'DrMundo', name: 'ドクター・ムンド', icon: '/images/champion/DrMundo.png' },
  { key: 'Draven', id: 'Draven', name: 'ドレイヴン', icon: '/images/champion/Draven.png' },
  { key: 'Ekko', id: 'Ekko', name: 'エコー', icon: '/images/champion/Ekko.png' },
  { key: 'Elise', id: 'Elise', name: 'エリス', icon: '/images/champion/Elise.png' },
  { key: 'Evelynn', id: 'Evelynn', name: 'イヴリン', icon: '/images/champion/Evelynn.png' },
  { key: 'Ezreal', id: 'Ezreal', name: 'エズリアル', icon: '/images/champion/Ezreal.png' },
  { key: 'Fiddlesticks', id: 'Fiddlesticks', name: 'フィドルスティックス', icon: '/images/champion/Fiddlesticks.png' },
  { key: 'Fiora', id: 'Fiora', name: 'フィオラ', icon: '/images/champion/Fiora.png' },
  { key: 'Fizz', id: 'Fizz', name: 'フィズ', icon: '/images/champion/Fizz.png' },
  { key: 'Galio', id: 'Galio', name: 'ガリオ', icon: '/images/champion/Galio.png' },
  { key: 'Gangplank', id: 'Gangplank', name: 'ガングプランク', icon: '/images/champion/Gangplank.png' },
  { key: 'Garen', id: 'Garen', name: 'ガレン', icon: '/images/champion/Garen.png' },
  { key: 'Gnar', id: 'Gnar', name: 'ナー', icon: '/images/champion/Gnar.png' },
  { key: 'Gragas', id: 'Gragas', name: 'グラガス', icon: '/images/champion/Gragas.png' },
  { key: 'Graves', id: 'Graves', name: 'グレイヴス', icon: '/images/champion/Graves.png' },
  { key: 'Gwen', id: 'Gwen', name: 'グウェン', icon: '/images/champion/Gwen.png' },
  { key: 'Hecarim', id: 'Hecarim', name: 'ヘカリム', icon: '/images/champion/Hecarim.png' },
  { key: 'Heimerdinger', id: 'Heimerdinger', name: 'ハイマーディンガー', icon: '/images/champion/Heimerdinger.png' },
  { key: 'Illaoi', id: 'Illaoi', name: 'イラオイ', icon: '/images/champion/Illaoi.png' },
  { key: 'Irelia', id: 'Irelia', name: 'イレリア', icon: '/images/champion/Irelia.png' },
  { key: 'Ivern', id: 'Ivern', name: 'アイバーン', icon: '/images/champion/Ivern.png' },
  { key: 'Janna', id: 'Janna', name: 'ジャンナ', icon: '/images/champion/Janna.png' },
  { key: 'JarvanIV', id: 'JarvanIV', name: 'ジャーバンIV', icon: '/images/champion/JarvanIV.png' },
  { key: 'Jax', id: 'Jax', name: 'ジャックス', icon: '/images/champion/Jax.png' },
  { key: 'Jayce', id: 'Jayce', name: 'ジェイス', icon: '/images/champion/Jayce.png' },
  { key: 'Jhin', id: 'Jhin', name: 'ジン', icon: '/images/champion/Jhin.png' },
  { key: 'Jinx', id: 'Jinx', name: 'ジンクス', icon: '/images/champion/Jinx.png' },
  { key: 'Kaisa', id: 'Kaisa', name: 'カイサ', icon: '/images/champion/Kaisa.png' },
  { key: 'Kalista', id: 'Kalista', name: 'カリスタ', icon: '/images/champion/Kalista.png' },
  { key: 'Karma', id: 'Karma', name: 'カルマ', icon: '/images/champion/Karma.png' },
  { key: 'Karthus', id: 'Karthus', name: 'カーサス', icon: '/images/champion/Karthus.png' },
  { key: 'Kassadin', id: 'Kassadin', name: 'カサディン', icon: '/images/champion/Kassadin.png' },
  { key: 'Katarina', id: 'Katarina', name: 'カタリナ', icon: '/images/champion/Katarina.png' },
  { key: 'Kayle', id: 'Kayle', name: 'ケイル', icon: '/images/champion/Kayle.png' },
  { key: 'Kayn', id: 'Kayn', name: 'ケイン', icon: '/images/champion/Kayn.png' },
  { key: 'Kennen', id: 'Kennen', name: 'ケネン', icon: '/images/champion/Kennen.png' },
  { key: 'KhaZix', id: 'KhaZix', name: 'カ＝ジックス', icon: '/images/champion/Khazix.png' },
  { key: 'Kindred', id: 'Kindred', name: 'キンドレッド', icon: '/images/champion/Kindred.png' },
  { key: 'Kled', id: 'Kled', name: 'クレッド', icon: '/images/champion/Kled.png' },
  { key: 'KogMaw', id: 'KogMaw', name: 'コグ＝マウ', icon: '/images/champion/KogMaw.png' },
  { key: 'LeBlanc', id: 'LeBlanc', name: 'ルブラン', icon: '/images/champion/Leblanc.png' },
  { key: 'LeeSin', id: 'LeeSin', name: 'リー・シン', icon: '/images/champion/LeeSin.png' },
  { key: 'Leona', id: 'Leona', name: 'レオナ', icon: '/images/champion/Leona.png' },
  { key: 'Lillia', id: 'Lillia', name: 'リリア', icon: '/images/champion/Lillia.png' },
  { key: 'Lissandra', id: 'Lissandra', name: 'リサンドラ', icon: '/images/champion/Lissandra.png' },
  { key: 'Lucian', id: 'Lucian', name: 'ルシアン', icon: '/images/champion/Lucian.png' },
  { key: 'Lulu', id: 'Lulu', name: 'ルル', icon: '/images/champion/Lulu.png' },
  { key: 'Lux', id: 'Lux', name: 'ラックス', icon: '/images/champion/Lux.png' },
  { key: 'Malphite', id: 'Malphite', name: 'マルファイト', icon: '/images/champion/Malphite.png' },
  { key: 'Malzahar', id: 'Malzahar', name: 'マルザハール', icon: '/images/champion/Malzahar.png' },
  { key: 'Maokai', id: 'Maokai', name: 'マオカイ', icon: '/images/champion/Maokai.png' },
  { key: 'MasterYi', id: 'MasterYi', name: 'マスター・イー', icon: '/images/champion/MasterYi.png' },
  { key: 'MissFortune', id: 'MissFortune', name: 'ミス・フォーチュン', icon: '/images/champion/MissFortune.png' },
  { key: 'Mordekaiser', id: 'Mordekaiser', name: 'モルデカイザー', icon: '/images/champion/Mordekaiser.png' },
  { key: 'Morgana', id: 'Morgana', name: 'モルガナ', icon: '/images/champion/Morgana.png' },
  { key: 'Nami', id: 'Nami', name: 'ナミ', icon: '/images/champion/Nami.png' },
  { key: 'Nasus', id: 'Nasus', name: 'ナサス', icon: '/images/champion/Nasus.png' },
  { key: 'Nautilus', id: 'Nautilus', name: 'ノーチラス', icon: '/images/champion/Nautilus.png' },
  { key: 'Neeko', id: 'Neeko', name: 'ニーコ', icon: '/images/champion/Neeko.png' },
  { key: 'Nidalee', id: 'Nidalee', name: 'ニダリー', icon: '/images/champion/Nidalee.png' },
  { key: 'Nilah', id: 'Nilah', name: 'ニーラ', icon: '/images/champion/Nilah.png' },
  { key: 'Nocturne', id: 'Nocturne', name: 'ノクターン', icon: '/images/champion/Nocturne.png' },
  { key: 'Nunu', id: 'Nunu', name: 'ヌヌ＆ウィルンプ', icon: '/images/champion/Nunu.png' },
  { key: 'Olaf', id: 'Olaf', name: 'オラフ', icon: '/images/champion/Olaf.png' },
  { key: 'Orianna', id: 'Orianna', name: 'オリアナ', icon: '/images/champion/Orianna.png' },
  { key: 'Ornn', id: 'Ornn', name: 'オーン', icon: '/images/champion/Ornn.png' },
  { key: 'Pantheon', id: 'Pantheon', name: 'パンテオン', icon: '/images/champion/Pantheon.png' },
  { key: 'Poppy', id: 'Poppy', name: 'ポッピー', icon: '/images/champion/Poppy.png' },
  { key: 'Pyke', id: 'Pyke', name: 'パイク', icon: '/images/champion/Pyke.png' },
  { key: 'Qiyana', id: 'Qiyana', name: 'キアナ', icon: '/images/champion/Qiyana.png' },
  { key: 'Quinn', id: 'Quinn', name: 'クイン', icon: '/images/champion/Quinn.png' },
  { key: 'Rakan', id: 'Rakan', name: 'ラカン', icon: '/images/champion/Rakan.png' },
  { key: 'Rammus', id: 'Rammus', name: 'ラムス', icon: '/images/champion/Rammus.png' },
  { key: 'RekSai', id: 'RekSai', name: 'レク＝サイ', icon: '/images/champion/RekSai.png' },
  { key: 'Rell', id: 'Rell', name: 'レル', icon: '/images/champion/Rell.png' },
  { key: 'Renekton', id: 'Renekton', name: 'レネクトン', icon: '/images/champion/Renekton.png' },
  { key: 'Rengar', id: 'Rengar', name: 'レンガー', icon: '/images/champion/Rengar.png' },
  { key: 'Riven', id: 'Riven', name: 'リヴェン', icon: '/images/champion/Riven.png' },
  { key: 'Rumble', id: 'Rumble', name: 'ランブル', icon: '/images/champion/Rumble.png' },
  { key: 'Ryze', id: 'Ryze', name: 'ライズ', icon: '/images/champion/Ryze.png' },
  { key: 'Samira', id: 'Samira', name: 'サミーラ', icon: '/images/champion/Samira.png' },
  { key: 'Sejuani', id: 'Sejuani', name: 'セジュアニ', icon: '/images/champion/Sejuani.png' },
  { key: 'Senna', id: 'Senna', name: 'セナ', icon: '/images/champion/Senna.png' },
  { key: 'Seraphine', id: 'Seraphine', name: 'セラフィーン', icon: '/images/champion/Seraphine.png' },
  { key: 'Sett', id: 'Sett', name: 'セト', icon: '/images/champion/Sett.png' },
  { key: 'Shaco', id: 'Shaco', name: 'シャコ', icon: '/images/champion/Shaco.png' },
  { key: 'Shen', id: 'Shen', name: 'シェン', icon: '/images/champion/Shen.png' },
  { key: 'Shyvana', id: 'Shyvana', name: 'シヴァーナ', icon: '/images/champion/Shyvana.png' },
  { key: 'Singed', id: 'Singed', name: 'シンジド', icon: '/images/champion/Singed.png' },
  { key: 'Sion', id: 'Sion', name: 'サイオン', icon: '/images/champion/Sion.png' },
  { key: 'Sivir', id: 'Sivir', name: 'シヴィア', icon: '/images/champion/Sivir.png' },
  { key: 'Skarner', id: 'Skarner', name: 'スカーナー', icon: '/images/champion/Skarner.png' },
  { key: 'Sona', id: 'Sona', name: 'ソナ', icon: '/images/champion/Sona.png' },
  { key: 'Soraka', id: 'Soraka', name: 'ソラカ', icon: '/images/champion/Soraka.png' },
  { key: 'Swain', id: 'Swain', name: 'スウェイン', icon: '/images/champion/Swain.png' },
  { key: 'Sylas', id: 'Sylas', name: 'サイラス', icon: '/images/champion/Sylas.png' },
  { key: 'Syndra', id: 'Syndra', name: 'シンドラ', icon: '/images/champion/Syndra.png' },
  { key: 'TahmKench', id: 'TahmKench', name: 'タム・ケンチ', icon: '/images/champion/TahmKench.png' },
  { key: 'Taliyah', id: 'Taliyah', name: 'タリヤ', icon: '/images/champion/Taliyah.png' },
  { key: 'Talon', id: 'Talon', name: 'タロン', icon: '/images/champion/Talon.png' },
  { key: 'Taric', id: 'Taric', name: 'タリック', icon: '/images/champion/Taric.png' },
  { key: 'Teemo', id: 'Teemo', name: 'ティーモ', icon: '/images/champion/Teemo.png' },
  { key: 'Thresh', id: 'Thresh', name: 'スレッシュ', icon: '/images/champion/Thresh.png' },
  { key: 'Tristana', id: 'Tristana', name: 'トリスターナ', icon: '/images/champion/Tristana.png' },
  { key: 'Trundle', id: 'Trundle', name: 'トランドル', icon: '/images/champion/Trundle.png' },
  { key: 'Tryndamere', id: 'Tryndamere', name: 'トリンダメア', icon: '/images/champion/Tryndamere.png' },
  { key: 'TwistedFate', id: 'TwistedFate', name: 'ツイステッド・フェイト', icon: '/images/champion/TwistedFate.png' },
  { key: 'Twitch', id: 'Twitch', name: 'ツイッチ', icon: '/images/champion/Twitch.png' },
  { key: 'Udyr', id: 'Udyr', name: 'ウディア', icon: '/images/champion/Udyr.png' },
  { key: 'Urgot', id: 'Urgot', name: 'アーゴット', icon: '/images/champion/Urgot.png' },
  { key: 'Varus', id: 'Varus', name: 'ヴァルス', icon: '/images/champion/Varus.png' },
  { key: 'Vayne', id: 'Vayne', name: 'ヴェイン', icon: '/images/champion/Vayne.png' },
  { key: 'Veigar', id: 'Veigar', name: 'ベイガー', icon: '/images/champion/Veigar.png' },
  { key: 'Velkoz', id: 'Velkoz', name: 'ヴェルコズ', icon: '/images/champion/Velkoz.png' },
  { key: 'Vex', id: 'Vex', name: 'ヴェックス', icon: '/images/champion/Vex.png' },
  { key: 'Vi', id: 'Vi', name: 'ヴァイ', icon: '/images/champion/Vi.png' },
  { key: 'Viktor', id: 'Viktor', name: 'ヴィクター', icon: '/images/champion/Viktor.png' },
  { key: 'Vladimir', id: 'Vladimir', name: 'ブラッドミア', icon: '/images/champion/Vladimir.png' },
  { key: 'Volibear', id: 'Volibear', name: 'ボリベア', icon: '/images/champion/Volibear.png' },
  { key: 'Warwick', id: 'Warwick', name: 'ワーウィック', icon: '/images/champion/Warwick.png' },
  { key: 'Wukong', id: 'Wukong', name: 'ウーコン', icon: '/images/champion/Wukong.png' },
  { key: 'Xayah', id: 'Xayah', name: 'ザヤ', icon: '/images/champion/Xayah.png' },
  { key: 'Xerath', id: 'Xerath', name: 'ゼラス', icon: '/images/champion/Xerath.png' },
  { key: 'XinZhao', id: 'XinZhao', name: 'シン・ジャオ', icon: '/images/champion/XinZhao.png' },
  { key: 'Yasuo', id: 'Yasuo', name: 'ヤスオ', icon: '/images/champion/Yasuo.png' },
  { key: 'Yone', id: 'Yone', name: 'ヨネ', icon: '/images/champion/Yone.png' },
  { key: 'Yorick', id: 'Yorick', name: 'ヨリック', icon: '/images/champion/Yorick.png' },
  { key: 'Yuumi', id: 'Yuumi', name: 'ユーミ', icon: '/images/champion/Yuumi.png' },
  { key: 'Zac', id: 'Zac', name: 'ザック', icon: '/images/champion/Zac.png' },
  { key: 'Zed', id: 'Zed', name: 'ゼド', icon: '/images/champion/Zed.png' },
  { key: 'Zeri', id: 'Zeri', name: 'ゼリ', icon: '/images/champion/Zeri.png' },
  { key: 'Ziggs', id: 'Ziggs', name: 'ジグス', icon: '/images/champion/Ziggs.png' },
  { key: 'Zilean', id: 'Zilean', name: 'ジリアン', icon: '/images/champion/Zilean.png' },
  { key: 'Zoe', id: 'Zoe', name: 'ゾーイ', icon: '/images/champion/Zoe.png' },
  { key: 'Zyra', id: 'Zyra', name: 'ザイラ', icon: '/images/champion/Zyra.png' },
  { key: 'Viego', id: 'Viego', name: 'ヴィエゴ', icon: '/images/champion/Viego.png' },
  { key: 'Renata', id: 'Renata', name: 'レナータ・グラスク', icon: '/images/champion/Renata.png' },
  { key: 'Ksante', id: 'Ksante', name: 'カサンテ', icon: '/images/champion/KSante.png' },
  { key: 'Naafiri', id: 'Naafiri', name: 'ナフィーリ', icon: '/images/champion/Naafiri.png' },
  { key: 'Milio', id: 'Milio', name: 'ミリオ', icon: '/images/champion/Milio.png' },
  { key: 'Ambessa', id: 'Ambessa', name: 'アンベッサ', icon: '/images/champion/Ambessa.png' },
  { key: 'Aurora', id: 'Aurora', name: 'オーロラ', icon: '/images/champion/Aurora.png' },
  { key: 'Briar', id: 'Briar', name: 'ブライアー', icon: '/images/champion/Briar.png' },
  { key: 'Hwei', id: 'Hwei', name: 'フェイ', icon: '/images/champion/Hwei.png' },
  { key: 'Mel', id: 'Mel', name: 'メル', icon: '/images/champion/Mel.png' },
  { key: 'Smolder', id: 'Smolder', name: 'スモルダー', icon: '/images/champion/Smolder.png' },
  { key: 'Yunara', id: 'Yunara', name: 'ユナラ', icon: '/images/champion/Yunara.png' },
];

/**
 * 互換性のために Promise を返すヘルパーも用意しています。
 * 既存コードが fetch で非同期に取得していた場合に差し替えやすいです。
 */
export function getLocalChampions(): Promise<Champion[]> {
  return Promise.resolve(CHAMPIONS);
}